## 0. Read Files

In [1]:
import pandas as pd
import numpy as np

In [ ]:
df_testing = pd.read_csv('../Tbrain_Insurance/testing-set.csv')
#df_all = pd.read_csv('../Tbrain_Insurance/df_all.csv')
df_all = pd.read_csv('../Tbrain_Insurance/df_policy_claim_unuique.csv')

In [3]:
df_all.shape

(351273, 704)

In [4]:
# nan_count = df_all.isnull().sum()
# nan_count[nan_count > 0]

In [5]:
# replace target: 
replace_date = {'09/2658','10/2622','02/2611','11/2602', '10/2582', '10/2581', '04/2579', '08/2569', '10/2521',
 '11/2512', '01/2512', '10/2472','08/2471', '11/2464', '03/2464', '12/2453', '01/2442', '07/2280', '02/2152'}
print(len(replace_date))
replace_date_set = set(replace_date)
print(len(replace_date_set))

19
19


In [6]:
## convert to datetime formate
date_cols = ['DOB_of_Driver','Accident_Date','Accident_Time','ibirth', 'dbirth_new']


for input1 in replace_date_set:
    df_all[date_cols] = df_all[date_cols].replace(input1, pd.to_datetime('01/2017', format ='%m/%Y'))
df_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 351273 entries, 0 to 351272
Columns: 704 entries, Policy_Number to 2CSD3meanIO
dtypes: float64(557), int64(141), object(6)
memory usage: 1.8+ GB


In [7]:
## fill datetime value for date_cols 
df_all[date_cols] = df_all[date_cols].fillna(pd.to_datetime('01/2017', format ='%m/%Y'))
df_all[date_cols].head()

DOB_of_Driver        Accident_Date        Accident_Time      ibirth  \
0  2017-01-01 00:00:00  2017-01-01 00:00:00  2017-01-01 00:00:00  1980-11-01   
1  2017-01-01 00:00:00  2017-01-01 00:00:00  2017-01-01 00:00:00  1956-11-01   
2  2017-01-01 00:00:00  2017-01-01 00:00:00  2017-01-01 00:00:00  1954-03-01   
3  2017-01-01 00:00:00  2017-01-01 00:00:00  2017-01-01 00:00:00  1978-09-01   
4  2017-01-01 00:00:00  2017-01-01 00:00:00  2017-01-01 00:00:00  1960-10-01   

   dbirth_new  
0  1980-11-01  
1  1982-03-01  
2  1954-03-01  
3  1978-09-01  
4  1960-10-01

In [8]:
## convert to datetime formate
date_cols = ['DOB_of_Driver','Accident_Date','Accident_Time','ibirth', 'dbirth_new']

df = df_all

date_col=['ibirth', 'dbirth_new']
for col in date_col:
    df[col] =  pd.to_datetime(df[col], format='%Y-%m-%d', errors='ignore')  #'%Y-%m-%d %H:%M:%S'   #errors='coerce'


    
date_col=['DOB_of_Driver', 'ibirth', 'dbirth_new']
for col in date_col:
    df[col] =  pd.to_datetime(df[col], format='%m/%Y', errors='ignore')  #'%Y-%m-%d %H:%M:%S'   #errors='coerce'

date_col=['Accident_Date']
for col in date_col:
    df[col] =  pd.to_datetime(df[col], format='%Y/%m', errors='ignore')  #'%Y-%m-%d %H:%M:%S'   #errors='coerce'

date_col=['Accident_Time']
for col in date_col:
    df[col] =  pd.to_datetime(df[col], format='%H:%M', errors='ignore')  #'%Y-%m-%d %H:%M:%S'   #errors='coerce'

df[date_cols].info(verbose= True)
df_all = df

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 351273 entries, 0 to 351272
Data columns (total 5 columns):
DOB_of_Driver    351273 non-null datetime64[ns]
Accident_Date    351273 non-null datetime64[ns]
Accident_Time    351273 non-null datetime64[ns]
ibirth           351273 non-null datetime64[ns]
dbirth_new       351273 non-null datetime64[ns]
dtypes: datetime64[ns](5)
memory usage: 13.4 MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 351273 entries, 0 to 351272
Columns: 704 entries, Policy_Number to 2CSD3meanIO
dtypes: datetime64[ns](5), float64(557), int64(141), object(1)
memory usage: 1.8+ GB


In [9]:
df = df.drop(date_cols, axis =1)

In [10]:
df_all = df

In [11]:
df_all.isnull().sum().sum()

152685742

In [12]:
df_all = df_all.fillna(0)
df_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 351273 entries, 0 to 351272
Columns: 699 entries, Policy_Number to 2CSD3meanIO
dtypes: float64(557), int64(141), object(1)
memory usage: 1.8+ GB


In [ ]:
## combine Classifier result to Regression Model 

In [54]:
DF = pd.read_csv('../Tbrain_Insurance/Classifier.csv')     ##
DF.head()

Policy_Number  Next_Premium
0  55789b8f86893761c9aa9e7bf17938e737decc68             1
1  b6df13a3384528ba6339c52b4fff7c149de68011             1
2  e112d926103147bcdcb6dab201b736185a3e2520             0
3  aa346fa4b1931d1c7a55f8e1bca40b0927dd65ac             1
4  39c4d5daaa791676ec5559c9066d7e8e8dfc51d7             1

In [59]:
# print(df_all.shape)
# df_all = df_all.merge(DF, on = 'Policy_Number', how = 'left' ,suffixes=('','_Bi'))
# print(df_all.shape)

# print(df_all.shape)
# df_all = df_all.drop(['Next_Premium_Bi'], axis =1) 
# print(df_all.shape)

(351273, 699)
(351273, 700)


(351273, 699)
(351273, 698)


In [101]:
df_all = df_all.drop(['cont_ratio'], axis =1) 

## Nature & Juridical

In [140]:
# Nature
df1 = df_all[(df_all['fsex_1']==1)|(df_all['fsex_2']==1)]

df_train1 = df1[df1['Next_Premium']!=100]
print(df_train1.shape)
df_test1 = df1[df1['Next_Premium']==100]
print(df_test1.shape)
print(df_train1.shape[0]+df_test1.shape[0])
print(df1.shape[0])

# Juridical
df2 = df_all[(df_all['fsex_ ']==1)]
df2 = df2.drop(['i_age', 'd_age'], axis=1)    ######

df_train2 = df2[df2['Next_Premium']!=100]
print(df_train2.shape)
df_test2 = df2[df2['Next_Premium']==100]
print(df_test2.shape)
print(df_train2.shape[0]+df_test2.shape[0])
print(df2.shape[0])

(174910, 698)
(120048, 698)
294958
294958
(35853, 696)
(20462, 696)
56315
56315


In [141]:
# ### Optional 
# # downsampling
# df_train = df_train.sample(10000).reset_index()
# df_train = df_train[df_train.columns[1:]]
# df_train.head()
# # df_test = df_test.sample (1400).reset_index()

In [142]:
y1=df_train1['Next_Premium']
y1.head()

0     4414
1     8236
2     6153
3    12135
4     4345
Name: Next_Premium, dtype: int64

In [143]:
y2=df_train2['Next_Premium']
y2.head()

34     2869
44     1665
47     3841
65        0
115    6383
Name: Next_Premium, dtype: int64

In [144]:
#### train_ID1 = df_train1['Policy_Number']
df_train1 = df_train1.drop(['Policy_Number'], axis=1)
print(df_train1.shape)
print(train_ID1.shape)

train_ID2 = df_train2['Policy_Number']
df_train2 = df_train2.drop(['Policy_Number'], axis=1)
print(df_train2.shape)
print(train_ID2.shape)

(174910, 697)
(174910,)
(35853, 695)
(35853,)


In [145]:
df_test1=df_test1.drop(['Next_Premium'], axis=1)
print(df_test1.shape)

df_test2=df_test2.drop(['Next_Premium'], axis=1)
print(df_test2.shape)

(120048, 697)
(20462, 695)


In [146]:
test_ID1=df_test1['Policy_Number']
df_test1=df_test1.drop(['Policy_Number'], axis=1)
print(df_test1.shape)
print(test_ID1.shape)

test_ID2=df_test2['Policy_Number']
df_test2=df_test2.drop(['Policy_Number'], axis=1)
print(df_test2.shape)
print(test_ID2.shape)

(120048, 696)
(120048,)
(20462, 694)
(20462,)


## Reduce Dimension 

In [147]:
train1 = df_train1.drop(['Next_Premium'], axis=1)
test1 = df_test1
y_train1 = y1

train2 = df_train2.drop(['Next_Premium'], axis=1)
test2 = df_test2
y_train2 = y2

In [148]:
print(train1.shape)
print(test1.shape)
print(y1.shape)

print(train2.shape)
print(test2.shape)
print(y2.shape)

(174910, 696)
(120048, 696)
(174910,)
(35853, 694)
(20462, 694)
(35853,)


In [149]:
# import matplotlib.pyplot as plt
 
# ## standarlization
# from sklearn.preprocessing import StandardScaler
# stdsc = StandardScaler()
# train_std = stdsc.fit_transform(train)
# test_std = stdsc.fit_transform(test)
 
# X_std = train_std

#     #求共變異係數矩陣
# cov_mat = np.cov(X_std.T)
# print("共變異係數矩陣.shape=",cov_mat.shape)

 
# #求共變異係數矩陣 的特徵向量及特徵值
# eigen_vals, eigen_vecs = np.linalg.eig(cov_mat)
# print("特徵向量.shape=",eigen_vecs.shape)

 
# #計算解釋變異數比率 各特徵值/特徵值總和
# tot = sum(eigen_vals)
# var_exp = [(i / tot) for i in sorted(eigen_vals, reverse=True)]
# cum_var_exp = np.cumsum(var_exp)

# # Make a list of (eigenvalue, eigenvector) tuples
# eigen_pairs = [(np.abs(eigen_vals[i]), eigen_vecs[:, i])
#                for i in range(len(eigen_vals))]

# print("特徵值，特徵向量length：",len(eigen_pairs))
# eigen_pairs.sort(key=lambda k: k[0], reverse=True)

# #保留兩個最具影響力的特徵向量組成13x2 的投影矩陣W
# w = np.hstack((eigen_pairs[0][1][:, np.newaxis],
#                eigen_pairs[1][1][:, np.newaxis]))

# train_pca = X_std.dot(w)
# ###################################

# X_std = test_std

#     #求共變異係數矩陣
# cov_mat = np.cov(X_std.T)
# print("共變異係數矩陣.shape=",cov_mat.shape)

 
# #求共變異係數矩陣 的特徵向量及特徵值
# eigen_vals, eigen_vecs = np.linalg.eig(cov_mat)
# print("特徵向量.shape=",eigen_vecs.shape)

 
# #計算解釋變異數比率 各特徵值/特徵值總和
# tot = sum(eigen_vals)
# var_exp = [(i / tot) for i in sorted(eigen_vals, reverse=True)]
# cum_var_exp = np.cumsum(var_exp)

# # Make a list of (eigenvalue, eigenvector) tuples
# eigen_pairs = [(np.abs(eigen_vals[i]), eigen_vecs[:, i])
#                for i in range(len(eigen_vals))]

# print("特徵值，特徵向量length：",len(eigen_pairs))
# eigen_pairs.sort(key=lambda k: k[0], reverse=True)

# #保留兩個最具影響力的特徵向量組成13x2 的投影矩陣W
# w = np.hstack((eigen_pairs[0][1][:, np.newaxis],
#                eigen_pairs[1][1][:, np.newaxis]))

# test_pca = X_std.dot(w)

In [150]:
# train = train_pca
# test = test_pca
# y_train = y

### Modelling

In [151]:
from sklearn.linear_model import ElasticNet, Lasso,  BayesianRidge, LassoLarsIC
from sklearn.ensemble import RandomForestRegressor,  GradientBoostingRegressor
from sklearn.kernel_ridge import KernelRidge
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import RobustScaler
from sklearn.base import BaseEstimator, TransformerMixin, RegressorMixin, clone
from sklearn.model_selection import KFold, cross_val_score, train_test_split
from sklearn.metrics import mean_absolute_error
from sklearn.exceptions import ConvergenceWarning
import xgboost as xgb
import lightgbm as lgb

import warnings
warnings.filterwarnings(action='ignore', category=ConvergenceWarning)


In [152]:
#Validation function
n_folds = 5

def mae_cv1(model):
    kf = KFold(n_folds, shuffle=True, random_state=42).get_n_splits(train1.values)
    mae= (-cross_val_score(model, train1.values, y_train1.values, scoring="neg_mean_absolute_error", cv = kf))
    return(mae)

def mae_cv2(model):
    kf = KFold(n_folds, shuffle=True, random_state=42).get_n_splits(train2.values)
    mae= (-cross_val_score(model, train2.values, y_train2.values, scoring="neg_mean_absolute_error", cv = kf))
    return(mae)

In [153]:
# Base models

In [154]:
# # LASSO Regression :
# # This model may be very sensitive to outliers. So we need to made it more robust on them. For that we use the sklearn's Robustscaler() method on pipeline :
# lasso = make_pipeline(RobustScaler(), Lasso(alpha = 2, random_state=1))
# print("lasso mae: \n", mae)
# print("lasso score: {:.4f} ({:.4f})\n".format(mae.mean(), mae.std()))

In [155]:
# # Elastic Net Regression :
# # again made robust to outliers:
# #l1_list = [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1]
# ENet = make_pipeline(RobustScaler(), ElasticNet(alpha=2, l1_ratio=1, random_state=3))
# mae = mae_cv(ENet)
# print("ENet mae: \n", mae)
# print("ENet score: {:.4f} ({:.4f})\n".format(mae.mean(), mae.std()))

In [156]:
# #Kernel Ridge Regression :
# Kernel_list = ['linear','rbf','sigmoid','poly','laplacian','cosine','chi2']
# alpha_list = [0, 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1]

# KRR = KernelRidge(alpha = 0.02, kernel = 'cosine', degree = 0) 
# # mae = mae_cv(KRR)
# # print("KRR mae: \n", mae)
# # print("KRR score: {:.4f} ({:.4f})\n".format(mae.mean(), mae.std()))


In [157]:
# # With huber loss that makes it robust to outliers:
# GBoost = GradientBoostingRegressor()
# # mae = mae_cv(GBoost)
# # print("GBoost mae: \n", mae)
# # print("GBoost score: {:.4f} ({:.4f})\n".format(mae.mean(), mae.std()))

In [158]:
# # Averaged base models class
# class AveragingModels(BaseEstimator, RegressorMixin, TransformerMixin):
#     def __init__(self, models):
#         self.models = models
        
#     # we define clones of the original models to fit the data in
#     def fit(self, X, y):
#         self.models_ = [clone(x) for x in self.models]
        
#         # Train cloned base models
#         for model in self.models_:
#             model.fit(X, y)

#         return self
    
#     #Now we do the predictions for cloned models and average them
#     def predict(self, X):
#         predictions = np.column_stack([
#             model.predict(X) for model in self.models_
#         ])
#         return np.mean(predictions, axis=1) 

In [159]:
## mae Score

In [160]:
# mae = mae_cv(lasso)
# mae_lasso = mae 
# print("lasso mae: \n", mae)
# print("lasso score: {:.4f} ({:.4f})\n".format(mae.mean(), mae.std()))

In [161]:
# lasso mae: 
#  [ 1650.25138092  2758.60603395  2507.70387202  2472.04363955  2150.09175628]
# lasso score: 2307.7393 (381.4199)

In [162]:
# mae = mae_cv(ENet)
# mae_ENet = mae
# print("ENet mae: \n", mae)
# print("ENet score: {:.4f} ({:.4f})\n".format(mae.mean(), mae.std()))

In [163]:
# ENet mae: 
#  [ 1647.98492773  2781.01160241  2516.92456053  2486.03839108  2164.61988768]
# ENet score: 2319.3159 (388.4906)

In [164]:
# mae = (mae_cv(KRR))
# mae_KRR = mae
# print("KRR mae: \n", mae)
# print("KRR score: {:.4f} ({:.4f})\n".format(mae.mean(), mae.std()))

In [165]:
# mae = mae_cv(GBoost)
# mae_GBoost = mae
# print("GBoost mae: \n", mae)
# print("GBoost score: {:.4f} ({:.4f})\n".format(mae.mean(), mae.std()))

In [166]:
# GBoost mae: 
#  [ 1461.50882094  2446.82567999  2218.31836897  2210.17782972  1910.665789  ]
# GBoost score: 2049.4993 (339.7626)

In [167]:
# # Averaged base models score
# averaged_models = AveragingModels(models = (lasso, ENet, GBoost))

In [168]:
# mae = mae_cv(averaged_models)
# mae_Avg = mae
# print(" Averaged base models: {:.4f} ({:.4f})\n".format(mae.mean(), mae.std()))

In [169]:
# Averaged base models: 2189.5514 (372.8555)

In [170]:
# #Meta-Model
# #Stacking averaged Models Class:
# class StackingAveragedModels(BaseEstimator, RegressorMixin, TransformerMixin):
#     def __init__(self, base_models, meta_model, n_folds=5):
#         self.base_models = base_models
#         self.meta_model = meta_model
#         self.n_folds = n_folds
   
#     # We again fit the data on clones of the original models
#     def fit(self, X, y):
#         self.base_models_ = [list() for x in self.base_models]
#         self.meta_model_ = clone(self.meta_model)
#         kfold = KFold(n_splits=self.n_folds, shuffle=True, random_state=156)
        
#         # Train cloned base models then create out-of-fold predictions
#         # that are needed to train the cloned meta-model
#         out_of_fold_predictions = np.zeros((X.shape[0], len(self.base_models)))
#         for i, model in enumerate(self.base_models):
#             for train_index, holdout_index in kfold.split(X, y):
#                 instance = clone(model)
#                 self.base_models_[i].append(instance)
#                 instance.fit(X[train_index], y[train_index])
#                 y_pred = instance.predict(X[holdout_index])
#                 out_of_fold_predictions[holdout_index, i] = y_pred
                
#         # Now train the cloned  meta-model using the out-of-fold predictions as new feature
#         self.meta_model_.fit(out_of_fold_predictions, y)
#         return self
   
#     #Do the predictions of all base models on the test data and use the averaged predictions as 
#     #meta-features for the final prediction which is done by the meta-model
#     def predict(self, X):
#         meta_features = np.column_stack([
#             np.column_stack([model.predict(X) for model in base_models]).mean(axis=1)
#             for base_models in self.base_models_ ])
#         return self.meta_model_.predict(meta_features)

In [171]:
def mae_1(y1, y_pred1):
    return mean_absolute_error(y1,y_pred1)
def mae_2(y2, y_pred2):
    return mean_absolute_error(y2,y_pred2)

In [172]:
# # Stacking Averaged models Score

# stacked_averaged_models = StackingAveragedModels(base_models = (ENet, lasso, GBoost),  #ENet, lasso, KRR
#                                                  meta_model = GBoost) #GBoost

# mae = mae_cv(stacked_averaged_models)
# mae_stacked_avg = mae
# print("Stacking Averaged models score: {:.4f} ({:.4f})".format(mae.mean(), mae.std()))

In [173]:
# Stacking Averaged models score: 2042.9411 (339.1027)

In [174]:
# more models

In [175]:
# '''
# # lgb mae1: 
#  [ 1434.84210925  2260.83808605  2150.82386376  2179.23853216  1866.96877933]
# lgb score1: 1978.5423 (302.5589)

# lgb mae2: 
#  [ 3867.42438097  4014.83936575  3732.4610646   3878.76570465  3291.6854473 ]
# lgb score1: 3757.0352 (249.2474)

# '''

In [176]:
# LGBM :
model_lgb1 = lgb.LGBMRegressor(objective='regression')
mae1 = mae_cv1(model_lgb1)
mae_lgb1 = mae1
print("lgb mae1: \n", mae1)
print("lgb score1: {:.4f} ({:.4f})\n".format(mae1.mean(), mae1.std()))

model_lgb2 = lgb.LGBMRegressor(objective='regression')
mae2 = mae_cv2(model_lgb2)
mae_lgb2 = mae2
print("lgb mae2: \n", mae2)
print("lgb score1: {:.4f} ({:.4f})\n".format(mae2.mean(), mae2.std()))

lgb mae1: 
 [ 1434.19838608  2264.13989891  2154.20454303  2189.01533884  1870.35227644]
lgb score1: 1982.3821 (304.8487)

lgb mae2: 
 [ 3911.89496043  4021.96725171  3737.85396186  3880.84998805  3290.96836635]
lgb score1: 3768.7069 (255.5017)



In [177]:
model = model_lgb1  #

model.fit(train1, y_train1)
train_pred_lgb1 = model.predict(train1)
mae1 = mae_1(y_train1, train_pred_lgb1)  #
mae_lgb_train1 = mae1                                   #
print('mae_lgb on train1:', mae1) #

y_pred_lgb1 = model.predict(test1)  #

importances1 = model.feature_importances_
# std = np.std([tree.feature_importances_ for tree in model.estimators_], axis=0)
indices1 = np.argsort(importances1)[::-1]

# Print the feature ranking
print("Feature ranking:")

for f in range(7):   # train.shape[1]
    print("%d. feature %d.: %str (%2f)" % (f + 1, indices1[f], train1.columns[indices1[f]], importances1[indices1[f]]*100))

# # Plot the feature importances of the forest
# plt.figure()
# plt.title("Feature importances")
# plt.bar(range(train.shape[1]), importances[indices],
#        color="r") #, yerr=std[indices], align="center")
# plt.xticks(range(train.shape[1]), indices)
# plt.xlim([-1, train.shape[1]])
# plt.show()

model = model_lgb2  #
model.fit(train2, y_train2)
train_pred_lgb2 = model.predict(train2)
mae2 = mae_2(y_train2, train_pred_lgb2)  #
mae_lgb_train2 = mae2                                   #
print('mae_lgb on train2:', mae2) #

y_pred_lgb2 = model.predict(test2)  #

importances2 = model.feature_importances_
# std = np.std([tree.feature_importances_ for tree in model.estimators_], axis=0)
indices2 = np.argsort(importances2)[::-1]

# Print the feature ranking
print("Feature ranking:")

for f in range(7):   # train.shape[1]
    print("%d. feature %d.: %str (%2f)" % (f + 1, indices2[f], train2.columns[indices2[f]], importances2[indices2[f]]*100))



mae_lgb on train1: 1974.92916736
Feature ranking:
1. feature 111.: Premiumtr (66200.000000)
2. feature 7.: pdmg_acctr (28900.000000)
3. feature 21.: Premium_SumBtr (20900.000000)
4. feature 189.: I_P_ratio3tr (20800.000000)
5. feature 185.: Insured_Amount3tr (15400.000000)
6. feature 186.: Insured_AmountOtr (10500.000000)
7. feature 82.: Insured_Amount3_BSumtr (10000.000000)
mae_lgb on train2: 3715.49105034
Feature ranking:
1. feature 109.: Premiumtr (72700.000000)
2. feature 183.: Insured_Amount3tr (20900.000000)
3. feature 70.: fmarriage_ tr (16000.000000)
4. feature 189.: P_R_pctAtr (14700.000000)
5. feature 74.: Insured_Amount1_BSumtr (12100.000000)
6. feature 86.: Insured_Amount1_BStdtr (11500.000000)
7. feature 80.: Insured_Amount3_BSumtr (10400.000000)


In [ ]:
'''
mae_lgb on train1: 1969.9914609
Feature ranking:
1. feature 112.: Premiumtr (64800.000000)
2. feature 7.: pdmg_acctr (28300.000000)
3. feature 22.: Premium_SumBtr (20200.000000)
4. feature 190.: I_P_ratio3tr (18000.000000)
5. feature 19.: cont_ratiotr (17900.000000)
6. feature 186.: Insured_Amount3tr (15200.000000)
7. feature 188.: I_P_ratio1tr (10000.000000)
mae_lgb on train2: 3718.18953465
Feature ranking:
1. feature 110.: Premiumtr (73200.000000)
2. feature 19.: cont_ratiotr (24500.000000)
3. feature 71.: fmarriage_ tr (16400.000000)
4. feature 184.: Insured_Amount3tr (16300.000000)
5. feature 75.: Insured_Amount1_BSumtr (10600.000000)
6. feature 190.: P_R_pctAtr (9600.000000)
7. feature 81.: Insured_Amount3_BSumtr (8700.000000)
'''

In [99]:
# '''
# Xgboost mae: 
#  [ 1553.09530469  2401.15759272  2177.35396934  2174.6915555   1881.35674227]
# Xgboost score: 2037.5310 (293.1403)
# '''

In [100]:
# XGBoost :
model_xgb1 = xgb.XGBRegressor() #n_estimators=200
mae1 = mae_cv1(model_xgb1)
mae_xgb1 = mae2
print("Xgboost mae1: \n", mae1)
print("Xgboost score1: {:.4f} ({:.4f})\n".format(mae1.mean(), mae1.std()))

model_xgb2 = xgb.XGBRegressor() #n_estimators=200
mae2 = mae_cv2(model_xgb2)
mae_xgb2 = mae2
print("Xgboost mae2: \n", mae2)
print("Xgboost score2: {:.4f} ({:.4f})\n".format(mae2.mean(), mae2.std()))

KeyboardInterrupt: 

In [ ]:
# Xgboost mae: 
#  [ 2209.30725367  2330.14260246  2082.15111059  2190.86471294  2111.35915974]
# Xgboost score: 2184.7650 (86.8242)

In [ ]:
model = model_xgb1  #

model.fit(train1, y_train1)
train_pred_xgb1 = model.predict(train1)  #
mae1 = mae_1(y_train1, train_pred_xgb1)   #
mae_xgb_train1 = mae1                                   #
print('mae_xgb on train:', mae1) #

y_pred_xgb1 = model.predict(test1)  #

importances1 = model.feature_importances_
# std = np.std([tree.feature_importances_ for tree in model.estimators_], axis=0)
indices1 = np.argsort(importances1)[::-1]

# Print the feature ranking
print("Feature ranking:")

for f in range(7):   # train.shape[1]
    print("%d. feature %d.: %str (%2f)" % (f + 1, indices1[f], train1.columns[indices1[f]], importances1[indices1[f]]*100))


model = model_xgb2  #    
model.fit(train2, y_train2)
train_pred_xgb2 = model.predict(train2)  #
mae2 = mae_2(y_train2, train_pred_xgb2)   #
mae_xgb_train2 = mae2                                   #
print('mae_xgb on train:', mae2) #

y_pred_xgb2 = model.predict(test2)  #

importances2 = model.feature_importances_
# std = np.std([tree.feature_importances_ for tree in model.estimators_], axis=0)
indices2 = np.argsort(importances2)[::-1]

# Print the feature ranking
print("Feature ranking:")

for f in range(7):   # train.shape[1]
    print("%d. feature %d.: %str (%2f)" % (f + 1, indices2[f], train2.columns[indices2[f]], importances2[indices2[f]]*100))

# # Plot the feature importances of the forest
# plt.figure()
# plt.title("Feature importances")
# plt.bar(range(train.shape[1]), importances[indices],
#        color="r") #, yerr=std[indices], align="center")
# plt.xticks(range(train.shape[1]), indices)
# plt.xlim([-1, train.shape[1]])
# plt.show()

In [ ]:
# mae_xgb on train: 1924.18772008
# Feature ranking:
# 1. feature 166.: Premiumtr (19.466248)
# 2. feature 250.: Premium_meantr (8.163265)
# 3. feature 258.: Premium_Pred_Addtr (5.808477)
# 4. feature 72.: Replacement_cost_of_insured_vehicletr (4.709576)
# 5. feature 98.: Insured_Amount1tr (4.395605)
# 6. feature 71.: Engine_Displacement_(Cubic_Centimeter)tr (3.767661)
# 7. feature 165.: Coverage_Deductibletr (3.453689)

In [ ]:
# '''
# RandomForest mae: 
#  [ 1550.90146598  2462.00879027  2237.7326891   2258.35016851  1942.53006033]

# RandomForest score: 2090.3046 (316.5222)
# '''

In [ ]:
# # RF :
# model_rf = RandomForestRegressor(n_estimators=100)  # default n_estimators = 10
# mae = mae_cv(model_rf)
# mae_rf = mae
# print("RandomForest mae: \n", mae)
# print("\nRandomForest score: {:.4f} ({:.4f})\n".format(mae.mean(), mae.std()))

In [ ]:
# RandomForest mae: 
#  [ 1487.6104638   2423.44725241  2203.43303404  2212.03221765  1904.53282157]

# RandomForest score: 2046.2112 (324.5396)


In [ ]:
# model = model_rf  #

# model.fit(train, y_train)
# train_pred_rf = model.predict(train)  #
# mae = mae_(y_train, train_pred_rf)   #
# mae_rf_train = mae                                   #
# print('mae_rf on train:', mae) #

# y_pred_rf = model.predict(test)  #

# importances = model.feature_importances_
# #std = np.std([tree.feature_importances_ for tree in model_rf.estimators_], axis=0)
# indices = np.argsort(importances)[::-1]

# # Print the feature ranking
# print("Feature ranking:")

# for f in range(7):
#     print("%d. feature %d.: %str (%2f)" % (f + 1, indices[f], train.columns[indices[f]], importances[indices[f]]*100))

# # # Plot the feature importances of the forest
# # plt.figure()
# # plt.title("Feature importances")
# # plt.bar(range(train.shape[1]), importances[indices],
# #        color="r", yerr=std[indices], align="center")
# # plt.xticks(range(train.shape[1]), indices)
# # plt.xlim([-1, train.shape[1]])
# # plt.show()

In [ ]:
# mae_rf on train: 801.865598
# Feature ranking:
# 1. feature 166.: Premiumtr (29.192158)
# 2. feature 167.: Premium_Predtr (26.174226)
# 3. feature 258.: Premium_Pred_Addtr (8.405166)
# 4. feature 72.: Replacement_cost_of_insured_vehicletr (5.817675)
# 5. feature 71.: Engine_Displacement_(Cubic_Centimeter)tr (1.952259)
# 6. feature 242.: Insured_Amount1_meantr (1.222075)
# 7. feature 78.: aassured_ziptr (1.193084)

In [ ]:
# # Final Training and Prediction: 
# stacked_averaged_models.fit(train.values, y_train.values)
# stacked_train_pred = stacked_averaged_models.predict(train.values)
# stacked_pred = stacked_averaged_models.predict(test.values)

# print(mae_(y_train, stacked_train_pred))

In [ ]:
l = 0.3
x = 0.7
# r = 0.11
# s = 1- l - x - r
# ensemble_train = stacked_train_pred * s + train_pred_lgb *l + train_pred_xgb* x + train_pred_rf * r
# ensemble_test = stacked_pred * s + y_pred_lgb * l + y_pred_xgb * x + y_pred_rf *r

ensemble_train1 =  train_pred_lgb1 *l + train_pred_xgb1* x 
ensemble_test1 =  y_pred_lgb1 * l + y_pred_xgb1 * x 

ensemble_train2 =  train_pred_lgb2 *l + train_pred_xgb2* x 
ensemble_test2 =  y_pred_lgb2 * l + y_pred_xgb2 * x 

In [ ]:
print('MAE score on train data1:')  # 1844.5
print(mae_1(y_train1, ensemble_train1))

print('MAE score on train data2:')  # 1844.5
print(mae_2(y_train2, ensemble_train2))

In [ ]:
## prep submission

In [ ]:
#y_pred_stacked = pd.DataFrame(stacked_pred)
y_pred_lgb1 = pd.DataFrame(y_pred_lgb1)
y_pred_xgb1 = pd.DataFrame(y_pred_xgb1)
# y_pred_rf = pd.DataFrame(y_pred_rf)

y_pred1 = pd.DataFrame(ensemble_test1)

all_y1 = pd.concat([y_pred1,  y_pred_lgb1, y_pred_xgb1], axis=1)
all_y1.columns=['Final', 'lgb','xgb']
all_y1.to_csv('../Tbrain_Insurance/Reg_y1.csv')
all_y1.sample(10)

In [ ]:
#y_pred_stacked = pd.DataFrame(stacked_pred)
y_pred_lgb2 = pd.DataFrame(y_pred_lgb2)
y_pred_xgb2 = pd.DataFrame(y_pred_xgb2)
# y_pred_rf = pd.DataFrame(y_pred_rf)

y_pred2 = pd.DataFrame(ensemble_test2)

all_y2 = pd.concat([y_pred2,  y_pred_lgb2, y_pred_xgb2], axis=1)
all_y2.columns=['Final', 'lgb','xgb']
all_y2.to_csv('../Tbrain_Insurance/Reg_y2.csv')
all_y2.sample(10)

In [ ]:
all_y1.describe()

In [ ]:
all_y2.describe()

In [ ]:
# Negative -> 0 
b = all_y1[all_y1['Final']<0].shape[0]
a = b/all_y1.shape[0]*100
print(("negative prediction1 (#): %2d"%b))
print("negative prediction1 (Percent): %2f"%a)

b = all_y2[all_y2['Final']<0].shape[0]
a = b/all_y2.shape[0]*100
print(("negative prediction2 (#): %2d"%b))
print("negative prediction2 (Percent): %2f"%a)

In [ ]:
# condition1 = all_y['Final']<0
# all_y['Final'].loc[condition1] = 0
# all_y.describe()

In [ ]:
print(df_testing.shape)
print(test_ID1.shape)
print(y_pred1.shape)
print(test_ID2.shape)
print(y_pred2.shape)

In [ ]:
df1 = pd.DataFrame(test_ID1).reset_index()
# df1['Next_Premium'] = y_pred_lgb1
df1['Next_Premium'] = all_y1['Final']  ##

df2 = pd.DataFrame(test_ID2).reset_index()
# df2['Next_Premium'] = y_pred_lgb2
df2['Next_Premium'] = all_y2['Final'] ##

df = pd.concat([df1, df2], axis=0)
df = df_testing.merge(df, how = 'left', on = 'Policy_Number', suffixes=('_x','_y'))
DF = df.drop(['index','Next_Premium_x'], axis = 1)
DF.columns = df_testing.columns
DF.to_csv('../Tbrain_Insurance/testing-set_en.csv',index = False)     ##
DF.head()

In [ ]:
df1 = pd.DataFrame(test_ID1).reset_index()
# df1['Next_Premium'] = y_pred_lgb1
df1['Next_Premium'] = all_y1['lgb']  ##

df2 = pd.DataFrame(test_ID2).reset_index()
# df2['Next_Premium'] = y_pred_lgb2
df2['Next_Premium'] = all_y2['lgb'] ##

df = pd.concat([df1, df2], axis=0)
df.head()

df = df_testing.merge(df, how = 'left', on = 'Policy_Number', suffixes=('_x','_y'))
DF = df.drop(['index','Next_Premium_x'], axis = 1)
DF.columns = df_testing.columns
DF.to_csv('../Tbrain_Insurance/testing-set_lgb.csv',index = False)     ##
DF.head()

In [ ]:
df1 = pd.DataFrame(test_ID1).reset_index()
# df1['Next_Premium'] = y_pred_lgb1
df1['Next_Premium'] = all_y1['xgb']  ##

df2 = pd.DataFrame(test_ID2).reset_index()
# df2['Next_Premium'] = y_pred_lgb2
df2['Next_Premium'] = all_y2['xgb'] ##

df = pd.concat([df1, df2], axis=0)
df = df_testing.merge(df, how = 'left', on = 'Policy_Number', suffixes=('_x','_y'))
DF = df.drop(['index','Next_Premium_x'], axis = 1)
DF.columns = df_testing.columns
DF.to_csv('../Tbrain_Insurance/testing-set_xgb.csv',index = False)     ##
DF.head()